### ISSUE TITLE
Throws when run non-interactively

### ISSUE THREAD

**Issue by sindresorhus** [dominikwilkowski/cfonts#12]
When this module is used in a process that runs non-interactively (non-TTY, for example, when it's a child process), it throws:

```
TypeError {
    message: 'Cannot read property \'width\' of undefined',
  }

  Object.render (node_modules/cfonts/index.js:464:121)
```

I would suggest using [`term-size`](https://github.com/sindresorhus/term-size) instead of `window-size`, as it works even when non-TTY. Alternatively, you could fall back to a width of 80.

**Comment by dominikwilkowski** [comment]
Great suggestion, keep 'em coming. Will look into that when I get some time.
