### ISSUE TITLE
New lines inside CFonts.say()

### ISSUE THREAD

**Issue by alex-page** [dominikwilkowski/cfonts#15]
When using CFonts.say() I think it would be nice to be able to add a new line. An example of this might be:

```
CFonts.say( `Please some stuff \n Some stuff on a new line`, {
  font:  'console',
  align: 'center',
  colors: [ 'white' ],
});
```

I understand that you can do:
```
CFonts.say( `Please some stuff | Some stuff on a new line`, {
  font:  'console',
  align: 'center',
  colors: [ 'white' ],
});
```

Happy for this to be closed if it's not possible. I just thought it would be nice to mimic default `console.log` behaviour in this instance.

**Comment by dominikwilkowski** [comment]
The reason we use the pipe character for the new line `|` is because slashes inside a shell have to be escaped and become quickly unwieldy. So given that this is the lowest common denominator I decided that consistency would be best for the API. But maybe I can add that as well?
