### ISSUE TITLE
Can we also have support for apostrophe (' character)?

### ISSUE THREAD

**Issue by shobhitchittora** [dominikwilkowski/cfonts#17]

**Comment by dominikwilkowski** [comment]
Yeah that makes sense hey... Let me see when I get some time to add it to all fonts. Shouldn't take too long

**Comment by dominikwilkowski** [comment]
Just had some time and it was fun. :)  done!

**Comment by shobhitchittora** [comment]
@dominikwilkowski thanks for the response. Awesome work.
