### ISSUE TITLE
About license of porting library

### ISSUE THREAD

**Issue by frostming** [dominikwilkowski/cfonts#25]
As you may know, I am maintaining a Python port of cfonts.

At beginning, I just translate node js code to Python, but after the major refactor, I write my own code to implement new features.  I would like to know if I can apply a different license other than GPL2.0, say, MIT?

**Comment by dominikwilkowski** [comment]
Hey,

Sure thing, go ahead :)
I'd love this to still align though if that's possible. I'd love for both of the APIs to be the same and the font syntax to be the same. Means though that you will need to work on your gradient implementation.
But license-wise, go ahead.

**Comment by frostming** [comment]
Yes, their APIs are the same, despite the minor difference between two languages. Thanks for your reply.
