### ISSUE TITLE
Duplicate content in Supported Character

### ISSUE THREAD

**Issue by XieEDeHeiShou** [dominikwilkowski/cfonts#26]
![Duplicated content](https://user-images.githubusercontent.com/16363180/84353285-72d12a80-abf1-11ea-9d87-c00ef190a9ec.png)

Are these characters duplicated?
I'm sorry but I really cannot find out any difference between each other when using Chrome on Windows 10.

**Comment by dominikwilkowski** [comment]
Hi @XieEDeHeiShou 
Nice find. After looking at the README for so long I can't see little duplication like that anymore :D
I've fixed this now.
