### ISSUE TITLE
Is there any way to use this in python?

### ISSUE THREAD

**Issue by fun840** [dominikwilkowski/cfonts#35]
Sorry if this is a dumb question, but is there any way to use this in python? I can't just copy paste, it completely breaks. I know there's a version of this made in python, called python-cfonts, by frostming, but the gradients don't look good. I know the console supports more colors, but is there a way to use it in python? TIA!

**Comment by dominikwilkowski** [comment]
Hey @fun840 
I'm sorry I don't know Python well enough to help here.
I do know that the implementation of `python-cfonts` differs from my implementation as it's complex.
But maybe ask in that repo to see if frostming can help?
I'll close this issue for now but please feel free to reopen if I missed something.
