### ISSUE TITLE
Force color spectrum/support programmatically

### ISSUE THREAD

**Issue by firstdorsal** [dominikwilkowski/cfonts#37]
Is it possible to force the color spectrum/support programmatically?
If not would it be possible to add that?

Thank you for making our lifes more colorful <3

**Comment by dominikwilkowski** [comment]
Hey @firstdorsal 

Not sure if this is what you mean but you can force cfonts into a color mode to support more colors or less.
More here: https://github.com/dominikwilkowski/cfonts#consistency

Let me know if this fixes your issue or what you mean in more detail.

**Comment by firstdorsal** [comment]
yes you can do that with the environment variable when using it as a cli but how can you do that when using it as a library?

**Comment by dominikwilkowski** [comment]
You can set environment variables with node. Is that not what you want?
You can set the env var for your environment via the normal way:
```sh
$ FORCE_COLOR=3 node path/to/your/script.js
```

Of you can do it programmatically: 

```js
const cfonts = require('cfonts');

process.env['FORCE_COLOR'] = '3';

cfonts.say('Hello|world!', { font: 'tiny' });
```

I hope this helps. I will close this issue but please re-open it if I missed something.

**Comment by firstdorsal** [comment]
thank you!
this works but it requires access to the env variables and this is an extra permission for example for deno.
i would like to force the string/color generation even without environment variables just by setting it in the function:
```ts
cfonts.say('Hello|world!', { font: 'tiny',forceColor:3 });
```
