### ISSUE TITLE
Magenta color not working properly in this version

### ISSUE THREAD

**Issue by kderholtvisma** [dominikwilkowski/cfonts#58]
In version **3.1.0** this does not work
`cfonts "Not Working" --gradient "magenta",'#07d569',"#f80" -t --spaceless -a center`

Works fine in version **2.10.1**

**Comment by dominikwilkowski** [comment]
Hey @kderholtvisma 

I can't reproduce this. Can you send me a screenshot of what you're getting in your output?

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/1266923/177650629-e52a883d-5efc-43ba-97f0-7e26420d1a87.png">

**Comment by kderholtvisma** [comment]
When i type this with magenta, the text gets removed and this is the output 
![image](https://user-images.githubusercontent.com/75069313/177727980-8d8d802d-6ea6-4be2-93b7-642ae5876317.png)

If i remove magenta from the name and put red:
![image](https://user-images.githubusercontent.com/75069313/177728162-c663d407-74b2-4f16-b9d7-e048c15922a2.png)
That works.

This is with version **3.1.0**

If I install version **2.10.1**, this is the output
![image](https://user-images.githubusercontent.com/75069313/177728573-6d2de6cc-6997-4fd3-83f8-06d374d7aaaf.png)

After more digging it seems like the weird displaying is due to color support.
IF I set `TERM=xterm-256color`
and run the same command on version 3.1.0 it will show correct:
![image](https://user-images.githubusercontent.com/75069313/177728997-643e9d26-9146-412a-95f3-1572ea342efd.png)


So conclution is, if color is not supported in the terminal; version **2.10.1** will show text proper, while **3.1.0** will not. 


PS: this is inside a docker running on arm and not x86

**Comment by dominikwilkowski** [comment]
Ah yes now I can reproduce this! When I set env var to `FORCE_COLOR=1` then I can see the ANSI output for magenta is funky... Will fix now
Thanks for the report!

**Comment by dominikwilkowski** [comment]
This should be fixed now in `v3.1.1`
