### ISSUE TITLE
d.ts

### ISSUE THREAD

**Issue by Sunday9787** [dominikwilkowski/cfonts#60]
可以提供typescript  d.ts 类型声明吗？

**Comment by dominikwilkowski** [comment]
Hi @Sunday9787 
Do you speak english?
Google translate gave me this for your questions:
> Can typescript d.ts type declarations be provided?

I don't know much about Typescript but I do have a test in the repo that uses typescript to test the doc-comments and at some point we generated type definition files. Happy for you to add a PR if you know what you're doing?

**Comment by Sunday9787** [comment]
@dominikwilkowski 我英语超烂的
我懂你的意思，我可以试着 add a PR for type
