### ISSUE TITLE
Add typescript support for nodejs

### ISSUE THREAD

**Issue by TheElegantCoding** [dominikwilkowski/cfonts#64]

**Comment by dominikwilkowski** [comment]
I accept PRs and I [use ts to test the types](https://github.com/dominikwilkowski/cfonts/blob/released/nodejs/package.json#L31) we get from jsdocs but beyond that I won't be able to help here.

**Comment by dominikwilkowski** [comment]
Closing this for now. Do let me know if there is anything wrong specifically.
