### ISSUE TITLE
color detection not working as intended?

### ISSUE THREAD

**Issue by macau23** [dominikwilkowski/cfonts#68]
If I set TERM=xterm-256color or TERM=xterm, I don't get a smooth gradient transition, but it works if I set FORCE_COLOR=3.

Does this mean color detection is not working as intended?

**Comment by dominikwilkowski** [comment]
Hey, 256 color support is different to 16m color support though. I wonder if your terminal supports 16m colors but sets the flag for 256 colors only? But there is also a new major version of the dependency I use to detect this [supports-color](https://github.com/zkat/supports-color). Do you have any way to test version 2 out and see if that fixes that issue at all? It's hard to test for me as I don't have your terminal.

**Comment by macau23** [comment]
I can certainly try version 2, but I am new to rust, can you give me something to copy/paste to do this?

Edit: I am using mobaxterm which supports truecolor, but I guess TERM is what I will concentrate on.

**Comment by macau23** [comment]
TERM=xterm-24bit does not change anything.

**Comment by dominikwilkowski** [comment]
Just create a new rust project via `cargo new colortest` then cd into the folder `cd colortest`.
Now run `cargo add supports_color` and add the code from the supports_color crate readme to the `src/main.rs` file:

```rust
use supports_color::Stream;

fn main() {
    if let Some(support) = supports_color::on(Stream::Stdout) {
        if support.has_16m {
            println!("16 million (RGB) colors are supported");
        } else if support.has_256 {
            println!("256 colors are supported.");
        } else if support.has_basic {
            println!("Only basic ANSI colors are supported.");
        }
    } else {
        println!("No color support.");
    }
}
```

Then run `cargo run` and post the output here.

**Comment by macau23** [comment]
Thanks. Here are the results:

```
$ export TERM=xterm
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running target/debug/colortest
Only basic ANSI colors are supported.

$ export TERM=xterm-256color
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running target/debug/colortest
256 colors are supported.

$ export TERM=zzz
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running target/debug/colortest
No color support.

$ unset TERM
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/colortest`
No color support.
```

lscolors (or a script that writes truecolor to the terminal) is working for each of these.

**Comment by dominikwilkowski** [comment]
Ok thank you for that. So when you do the same with `cfonts` do you get the same results in line with the results above? Have you tried `FORCE_COLOR` ([docs here](https://github.com/dominikwilkowski/cfonts#consistency))? I'm pretty sure that overrides all detection anyway and should give you what you want? Just set the env var in your terminal and persist it and it should work?

**Comment by macau23** [comment]
I am trying to report that cfonts is not detecting that my terminal can do truecolor when it can, but maybe the problem is that the TERM type does not help in determining that?
What TERM do you use to make it show truecolor?

Results for TERM with cfonts:

```
TERM=xterm cfonts "$HOSTNAME" --gradient red,yellow,red --transition-gradient # not truecolor, few colors
TERM=xterm256 cfonts "$HOSTNAME" --gradient red,yellow,red --transition-gradient # not truecolor, but more colors
TERM=vdsgsd cfonts "$HOSTNAME" --gradient red,yellow,red --transition-gradient # truecolor!
```
You can see that a non-existing TERM forces truecolor.

If I use FORCE_COLOR=3 (see top comment), cfonts shows truecolor.
If I set COLORTERM=truecolor it shows truecolor.

**Comment by dominikwilkowski** [comment]
I see what you're saying. Sorry that took me a minute. 
From the [GNU docs](https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html):

> Text windows today typically support at least 8 colors. Often, however, the text window supports 16 or more colors, even though the TERM variable is set to a identifier denoting only 8 supported colors.

So it seems the `TERM` env var isn't a great way to determine the color support of a terminal application. I use iTerm2 as my default and it shows `truecolor` by default. 

I just use the supports-color create that worries about those things. Might be good to open an issue there. Happy to switch to another way to detect color support if you have one that is more stable? The amount of terminal application out there is vast and I doubt any way is going to be fool proof here.

**Comment by macau23** [comment]
Okay I will open an issue there. One question: what does `echo "$COLORTERM"` return for you?

**Comment by dominikwilkowski** [comment]
> what does echo "$COLORTERM" return for you?

`truecolor` on iTerm2
```sh
λ echo "$COLORTERM"
truecolor
```

and nothing on the built in terminal app:
```sh
λ echo "$COLORTERM"

```

**Comment by macau23** [comment]
COLORTERM is the way.

**Comment by dominikwilkowski** [comment]
@macau23 by that you mean people should make sure they set the `COLORTERM` env var in their shells to make it all work?
