### ISSUE TITLE
error: unknown option `-t'

### ISSUE THREAD

**Issue by Chaz6** [dominikwilkowski/cfonts#7]
```
$ npm install -g cfonts
/home/chaz/.local/bin/cfonts -> /home/chaz/.local/lib/node_modules/cfonts/bin/font.js
/home/chaz/.local/lib
└── cfonts@1.1.2

$ which cfonts
~/.local/bin/cfonts

$ cfonts

 Ouch: Please provide text to convert with cfonts -t "Text"
       Run cfonts --help for more infos

$ cfonts -t "Text"

  error: unknown option `-t'
```

If I can provide any more useful information please let me know.

**Comment by dominikwilkowski** [comment]
Hey @Chaz6,

The `-t` option was deprecated in the [version 1.0.0 release](https://github.com/dominikwilkowski/cfonts/releases/tag/v1.0.0).

Now you can run cfonts with text just like this:

```shell
$  cfonts "Text"
```

**Comment by dominikwilkowski** [comment]
I think I need to fix the help text though ey? :)
Will do now

**Comment by Chaz6** [comment]
Great thank you!
