### ISSUE TITLE
How to create rainbow color

### ISSUE THREAD

**Issue by xiu8918** [dominikwilkowski/cfonts#74]

**Comment by dominikwilkowski** [comment]
If you're talking about the gradient then have a look at the docs here: https://github.com/dominikwilkowski/cfonts#-g---gradient

To make any font get the a gradient from color a to b just specify them:
```sh
cfonts "my text" -g red,blue
```
This will give you a gradient from left red to blue right.
Closing this issue now but feel free to re-open if there's more to this question.
