### ISSUE TITLE
Panic with gradient and font "console"

### ISSUE THREAD

**Issue by ropery** [dominikwilkowski/cfonts#75]
To reproduce:

    $ cfonts "$(seq 200)" -f console -g red,magenta
    thread 'main' panicked at src/gradient.rs:443:32:
    range end index 3 out of range for slice of length 2
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This bug depends on the width of the terminal and the length of the text.
If you can't reproduce the panic, try it in a narrower window or increase the `seq` argument.

**Comment by dominikwilkowski** [comment]
Thank you for reporting this. 
Fixed now in `v1.1.3rust` and live in cargo and will be pushed down the other pipelines (like brew, AUR etc) later today
