### ISSUE TITLE
Support Hexadecimal Colors

### ISSUE THREAD

**Issue by xxhomey19** [dominikwilkowski/cfonts#8]
Could you support sending Hexadecimal Color as font color and background color?

Thanks a lot!

**Comment by dominikwilkowski** [comment]
Hey @xxhomey19 

The command line interface (cli) only has limited support for colors in the first place. I use [chalk](https://github.com/chalk/chalk) in this project which tries to bring some consistency to the different cli.
Have a look at all supported colors at [their listing](https://github.com/chalk/chalk#colors).

These colors don't work with the colors you use in the browser unfortunately as hexdecimal colors are way more plentiful.

Hope this helps.

If you do know if a way to get more color support let me know, I'd be very interested and I'll reopen this then.
