### ISSUE TITLE
Mixed case console font

### ISSUE THREAD

**Issue by mrwwalmsley** [dominikwilkowski/cfonts#82]
The examples indicate that the console font can have upper and lower case.
But when I use it from the terminal or in a node JS app, I get all lowercase.

For example, the following brints the text in all lowercase:

` cfonts "BlaH" -f console`

Is something broken? Or is the example screenshot wrong?

**Comment by dominikwilkowski** [comment]
Hi there,
`cfonts` only supports [these characters](https://github.com/dominikwilkowski/cfonts?tab=readme-ov-file#supported-characters). Not sure what you mean by
> The examples indicate that the console font can have upper and lower case.

There are no lowercase characters basically but in some fonts the characters may look lowercase? `grid` as an example?
