### ISSUE TITLE
Rust build ... error font path ...

### ISSUE THREAD

**Issue by father-mande** [dominikwilkowski/cfonts#85]
Hi,

After a git clone, then cargo build --release ...
the generation fail due to  :  
    **Compiling cfonts v1.2.0 (/opt/from_git/rust/cfonts/rust)
error: couldn't read `src/../fonts/console.json`: No such file or directory (os error 2)
  --> src/font.rs:52:21
   |
52 |     let font_content = include_str!("../fonts/console.json");
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
help: there is a file with the same name in a different directory
   |
52 |     let font_content = include_str!("../../fonts/console.json");
   |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~**

This for all fonts ...
The PATH is incorrect ... to workaround ... I have created a link in **rust** folder to **../fonts**  folder (in **cfonts** directory.)

Philippe.

**Comment by dominikwilkowski** [comment]
Hi @father-mande 
You have to run the make command to run the repo locally. That's what the [Makefile](https://github.com/dominikwilkowski/cfonts/blob/released/rust/Makefile) is for
